name: "CodeQualityAndChecks"
on: push
jobs:
  code_quality:
    uses: ./.github/workflows/terraform_pre_commit.yml
    with:
      terraform-version: "~1.11"
      terragrunt-version: "0.73.13"
      tflint-version: "v0.55.1"
      terraform-docs-version: "v0.19.0"
